### ISSUE TITLE
Draft CLI client

### ISSUE THREAD

**Issue by coufalja** [jamf/regatta#68]
Regatta API is currently available only via gRPC calls which is inconvenient for debugging/development purposes. We should come up with either a standalone or embedded CLI that would lessen the burden of ordinary tasks (Get, Put, Del).

* Write down an RFC for change
* Outline the most critical use-cases
* DevEx design of the CLI

**Comment by Tantalor93** [comment]
Cheers, for those interested, I have implemented unofficial CLI client for Regatta https://github.com/Tantalor93/regatta-client

**Comment by Tantalor93** [comment]
see https://engineering.jamf.com/regatta/ecosystem/#cli-tool
