### ISSUE TITLE
deleted field in DeleteRangeResponse is not set correctly

### ISSUE THREAD

**Issue by Tantalor93** [jamf/regatta#94]
**Describe the bug**
`deleted` field is not set to correct number, when using `DeleteRange`  query as defined https://engineering.jamf.com/regatta/api/#deleterangeresponse
 
**To Reproduce**
1. create data in some table in Regatta
2. delete all data in the table using query like this
```
grpcurl -insecure "-d={\"table\": \"$(printf "dns-zones" | base64)\", \"key\": \"$(printf "\0" | base64)\", \"range_end\":\"$(printf "\0" | base64)\"}" localhost:8443  regatta.v1.KV/DeleteRange
```
3. eventhough data is deleted, the response does not even contain `deleted` field, see the response of grpcurl
```
{
  "header": {
    "shardId": "10016",
    "replicaId": "1",
    "revision": "35",
    "raftTerm": "3",
    "raftLeaderId": "1"
  }
}
```

**Expected behavior**
I would like the DeleteRangeResponse object as described in documentation https://engineering.jamf.com/regatta/api/#deleterangeresponse to contain correct number in `deleted` field

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: [e.g. Debian]
 - FS: [e.g. ext4]
 - Arch: [e.g. x86, ARM64]

**Additional context**
Feel free to contact me, if you need any additional details 🙂

**Comment by coufalja** [comment]
Thanks for reporting this, fix will land in 0.2.0.
